### PR TITLE
Api client generation

### PR DESCRIPTION
**Pull request by se7entyse7en**
Fixes client generation in Makefile and updates the client.

### CODE REVIEW

**Comment by se7entyse7en** [comment]
@dpordomingo I wanted to update the client first before adding bearer auth to make changes clearer.

**Comment by dpordomingo** [comment]
This is autogenerated code, isn't it?

**Comment by dpordomingo** [comment]
if that's the case, LGTM

**Comment by se7entyse7en** [comment]
@dpordomingo yup! autgenerated plus just a fix in path in Makefile after the refactor 👍 
merging then

**Pull request merged**
