### PR TITLE
Adding tooltips style guide for the charts

### PR DESCRIPTION
**Pull request by znegrin**
This PR is related to the issue [#ENG-306](https://athenianco.atlassian.net/browse/ENG-306). It adds a static page with all the layouts and examples of the chart tooltips, adding the necessary styles. It can be reviewed here: http://localhost:3000/tooltips

- Main page:

image

- User tooltip:

image

- Text and numbers:

image

image

- Pull requests:

image

image

image

- Repositories:

image

image

- Releases:

image

image

Signed-off-by: Zuri Negrín <zurinegrin@gmail.com>

### CODE REVIEW

**Comment by znegrin** [comment]
I updated this and it is now matching the new way to define the prototypes.
Thank you!

**Comment by se7entyse7en** [comment]
@dpordomingo is something blocking this?

**Comment by warenlg** [comment]
Can we merge this? once we fix the conflict ofc

**Comment by dpordomingo** [comment]
We planned to use [`wwayne/react-tooltip`](https://github.com/wwayne/react-tooltip) instead of jquery ones.
Let's merge and migrate when we start implementing them.

**Comment by dpordomingo** [comment]
Conflicts solved and push-forced to be on top of the current `master`.
`/insights` leftover was also removed.

**Pull request merged**
