### PR TITLE
Create starting point for Athenian webapp 

### PR DESCRIPTION
**Pull request by dpordomingo**
depends on #3
required by [ENG-14]

This PR implements a simple react app, serving Athenian simple content, that will be used as a starting point.

run it:
```bash
$ yarn start
```
and open http://localhost:3000/

image

## TODO

Something to be done in the next PR:
- pack this into the docker image, to be served by Nginx

[ENG-14]: https://athenianco.atlassian.net/browse/ENG-14

### CODE REVIEW

**Comment by dpordomingo** [comment]
build passes in my personal Travis account:
https://travis-ci.org/dpordomingo/athenian-webapp/builds/620631654

**Comment by se7entyse7en** [comment]
Great! Just one thing, why typescript? Can you redo it with js? Just because I personally don't know ts and I wouldn't be able to help you much otherwise, and I guess that also others in the team prefer js instead than ts.

**Comment by dpordomingo** [comment]
I used typescript because we already had experience with it; but ok, removed.
We can consider it later :D

**Comment by se7entyse7en** [comment]
@dpordomingo yup! Thanks a lot! And sorry for the revert, I should have been clearer.

**Comment by se7entyse7en** [comment]
Minor comment, do we need all the logos you added and the xcf file?

**Comment by dpordomingo** [comment]
We'll clean logos folder as soon as Zuri provides the official ones, and the final designs.
For this starting point it can help to have them to be flexible.

**Comment by dpordomingo** [comment]
Merging this at it seems there is no other concern.

**Pull request merged**
