### PR TITLE
feat(DEV-258): Implement search bar over GH labels and simulate its b…

### PR DESCRIPTION
**Pull request by navassouza**
…ehavior with mock data

### CODE REVIEW

**Comment by navassouza** [comment]
Screen Shot 2020-06-19 at 00 02 15

Ready to add the api call and some code cleanup

**Comment by navassouza** [comment]
Screen Shot 2020-06-19 at 14 15 56

**Comment by navassouza** [comment]
@se7entyse7en, this is the bare bones of the feature. Let me know when approved so I can start adding the feature in a new branch.
1) Add the api request
2) organize better the styles

**Comment by eiso** [comment]
Since it's on prototypes, any objection to merge this to staging?

**Comment by navassouza** [comment]
@eiso, none. Merging

**Pull request merged**
